name: publish

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image (pull_request)
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          build-args: COMMITHASH=${{ github.event.workflow_run.head_sha }}
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository }}:PR_${{ github.event.workflow_run.pull_requests[0].number }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image (push branch)
        if: ${{ github.event.workflow_run.event == 'push' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          build-args: COMMITHASH=${{ github.event.workflow_run.head_sha }}
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            ghcr.io/${{ github.repository }}:SHA_${{ github.event.workflow_run.head_sha }}
            ghcr.io/${{ github.repository }}:${{ github.event.workflow_run.head_branch == 'main' && 'main' || 'stable' }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image (push tag)
        if: ${{ github.event.workflow_run.event == 'release' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          build-args: |
            COMMITHASH=${{ github.event.workflow_run.head_sha }}
            VERSION=${{ github.event.workflow_run.display_title }}
          platforms: linux/amd64,linux/arm64/v8
          tags: ghcr.io/${{ github.repository }}:${{ github.event.workflow_run.display_title }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
